---
# .taskfile-data.yaml
# Optional configuration for dr task compose

# Development server ports
# Displayed when running the dev task
ports:
  - name: app_backend
    port: 8080
  - name: app_frontend
    port: 5173
  - name: infra
    port: 8090
