export const ACTION_TYPES = {
  HIDE_WELCOME_MODAL: 'HIDE_WELCOME_MODAL',
  SET_COLLAPSIBLE_PANEL_DEFAULT_OPEN: 'SET_COLLAPSIBLE_PANEL_DEFAULT_OPEN',
  SET_ENABLE_CHART_GENERATION: 'SET_ENABLE_CHART_GENERATION',
  SET_ENABLE_BUSINESS_INSIGHTS: 'SET_ENABLE_BUSINESS_INSIGHTS',
  SET_INCLUDE_CSV_BOM: 'SET_INCLUDE_CSV_BOM',
  SET_DATA_SOURCE: 'SET_DATA_SOURCE',
  SET_EXPAND_GRAPHS_INSIGHTS_DEFAULT_OPEN: 'SET_EXPAND_GRAPHS_INSIGHTS_DEFAULT_OPEN',
  SET_THEME: 'SET_THEME',
} as const;

export const STORAGE_KEYS = {
  HIDE_WELCOME_MODAL: 'HIDE_WELCOME_MODAL',
  COLLAPSIBLE_PANEL_DEFAULT_OPEN: 'COLLAPSIBLE_PANEL_DEFAULT_OPEN',
  ENABLE_CHART_GENERATION: 'ENABLE_CHART_GENERATION',
  ENABLE_BUSINESS_INSIGHTS: 'ENABLE_BUSINESS_INSIGHTS',
  INCLUDE_CSV_BOM: 'INCLUDE_CSV_BOM',
  DATA_SOURCE: 'DATA_SOURCE',
  EXPAND_GRAPHS_INSIGHTS_DEFAULT_OPEN: 'EXPAND_GRAPHS_INSIGHTS_DEFAULT_OPEN',
  THEME: 'THEME',
} as const;

export const DATA_TABS = {
  DESCRIPTION: 'description',
  RAW: 'raw',
};
